spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bankdb
    username: bank
    password: bank
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.xml

server:
  port: 8080

app:
  crypto:
    secret: ${APP_CRYPTO_SECRET}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"